forge 'forge.puppetlabs.com'

moduledir 'third_party'

mod 'puppetlabs-stdlib', '4.25.1'
mod 'thekevjames-homebrew', '1.8.1'
mod 'puppetlabs-vcsrepo', '2.3.0'
mod 'puppetlabs-apt', '6.0.0'
mod 'puppetlabs-postgresql', '5.9.0'
mod 'puppetlabs-concat', '4.2.1'
mod 'puppet-nodejs', '6.0.0'
mod 'edestecd-macports', '0.1.0'
